// src/app/construir/equipamentos/data.ts

export const detalhesEquipamentos: Record<string, any> = {
 "Impressora 3D FDM": {
  tags: ["Coworking", "Necessário treinamento"],
  descricao: "Utilizada para a fabricação de protótipos e peças funcionais por meio da deposição de filamento termoplástico, permitindo rápida materialização de modelos tridimensionais.",
  marca: "Bambu Lab",
  modelo: "X1-Carbon",
  volume: "256 x 256 x 256 (mm)",
  softwares: "Bambu Studio",
  materiais: ["PLA", "ABS", "PETG", "TPU"],
  uso: "Este dispositivo pode ser utilizado de forma autônoma; para isso, é necessário concluir o treinamento de segurança 'Impressora 3D: Impressora de Filamento', com duração de aproximadamente 30 a 60 minutos.",
  risco: "A cabeça de impressão pode atingir temperaturas de até 280°C durante a operação ou na fase de aquecimento/resfriamento, e a cama de impressão pode atingir temperaturas de até 140°C. Portanto, nunca coloque a mão na área de construção.",
  nivelRisco: 1,
},

"Impressora 3D SLA": {
  tags: ["Lab. CAD/CAE/CAM", "Necessário treinamento"],
  descricao: "Utilizada para a produção de peças com alto nível de detalhe e acabamento superficial, por meio da cura de resina fotossensível a partir de modelos digitais.",
  marca: "ELEGOO",
  modelo: "Saturn 4 Ultra",
  volume: "218 x 122 x 220 (mm)",
  softwares: "Chitu Box",
  materiais: ["Resina 405nm"],
  uso: "Este dispositivo pode ser utilizado de forma autônoma; para isso, é necessário concluir o treinamento de segurança 'Impressora 3D: Impressora de Resina', com duração de aproximadamente 60 minutos.",
  risco: "A resina fotossensível é irritante para pele e mucosas — utilize luvas e máscara durante o manuseio. A plataforma de impressão e o FEP aquecido podem causar queimaduras. Nunca exponha a resina líquida à luz ambiente sem proteção.",
  nivelRisco: 3,
},

"Cortadora a Laser CO2": {
  tags: ["Térreo Maker", "Necessário treinamento"],
  descricao: "Utilizada para o corte e a gravação de materiais por meio de laser CO2, permitindo a produção precisa de peças, componentes e elementos gráficos a partir de arquivos digitais.",
  marca: "DUE",
  modelo: "DUE Max",
  volume: "960 x 1530 x 305 (mm)",
  softwares: "DUE Studio",
  materiais: ["Madeiras", "MDF", "Tecido", "Couro", "Acrílico", "PETG"],
  uso: "Este dispositivo pode ser utilizado de forma autônoma; para isso, é necessário concluir o treinamento de segurança 'Corte a Laser', com duração de aproximadamente 30 a 60 minutos.",
  risco: "O equipamento opera com feixe de laser de alta potência e temperaturas elevadas, podendo gerar gases e vapores durante o corte dos materiais. A luz intensa e o calor representam risco de queimaduras e danos à visão, exigindo o uso de EPIs e ventilação adequada.",
  nivelRisco: 4,
},

"Gravadora Laser de Fibra": {
  tags: ["Lab. CAD/CAE/CAM", "Necessário treinamento"],
  descricao: "Utilizada para gravação de alta precisão em metais e materiais duros por meio de laser de fibra pulsado, ideal para marcação permanente de peças e componentes.",
  marca: "DUE",
  modelo: "Due Pulsa Pro 30W",
  volume: "N/A",
  softwares: "DUE Studio",
  materiais: ["Aço", "Alumínio", "Titânio", "Metais em geral"],
  uso: "Este dispositivo pode ser utilizado de forma autônoma; para isso, é necessário concluir o treinamento de segurança 'Gravação Laser de Fibra', com duração de aproximadamente 30 a 60 minutos.",
  risco: "O laser de fibra opera com potência elevada e emite radiação invisível ao olho humano, representando risco grave de danos permanentes à visão. O uso de óculos de proteção específicos para laser de fibra é obrigatório. O equipamento opera em gabinete fechado — nunca force a abertura durante a operação.",
  nivelRisco: 4,
},

"Router CNC": {
  tags: ["Térreo Maker", "Necessário treinamento"],
  descricao: "Utilizada para a usinagem de peças por remoção de material, permitindo a fabricação precisa de componentes a partir de modelos digitais em diferentes materiais.",
  marca: "A definir",
  modelo: "A definir",
  volume: "N/A",
  softwares: "A definir",
  materiais: ["Madeiras", "MDF", "Compensados"],
  uso: "Este dispositivo pode ser utilizado de forma autônoma; para isso, é necessário concluir o treinamento de segurança 'Router CNC', com duração de aproximadamente 30 a 60 minutos.",
  risco: "A operação da Router envolve ferramentas de corte em alta rotação, com risco de projeção de partículas, cortes e perfurações. O ruído elevado e a movimentação automática do equipamento exigem atenção constante e o uso adequado de EPIs.",
  nivelRisco: 4,
},

"Serra Esquadria": {
  tags: ["Lab. CAD/CAE/CAM", "Necessário treinamento"],
  descricao: "Utilizada para o corte preciso de materiais em ângulos retos ou inclinados, sendo ideal para acabamento e montagem de estruturas e componentes.",
  marca: "Bosch",
  modelo: "GCM254D",
  volume: "N/A",
  softwares: "N/A",
  materiais: ["Madeiras", "MDF", "Compensados", "Plásticos"],
  uso: "A utilização pode ser realizada de forma autônoma apenas por usuários que tenham concluído o treinamento específico e sigam rigorosamente os procedimentos de segurança.",
  risco: "A serra esquadria possui disco de corte em alta rotação, apresentando risco de cortes graves em caso de contato direto. Há também risco de projeção de partículas e ruído elevado durante a operação, sendo obrigatório o uso de EPIs e atenção total ao manuseio.",
  nivelRisco: 5,
},

"Serra Fita de Bancada": {
  tags: ["Lab. CAD/CAE/CAM", "Necessário treinamento"],
  descricao: "Utilizada para o corte de materiais como madeira, plásticos e chapas, permitindo cortes retos ou curvos com maior controle e precisão.",
  marca: "Makita",
  modelo: "LB1200F",
  volume: "N/A",
  softwares: "N/A",
  materiais: ["Madeiras", "MDF", "Compensados", "Plásticos"],
  uso: "A utilização pode ser realizada de forma autônoma apenas por usuários que tenham concluído o treinamento específico e estejam familiarizados com os procedimentos de segurança e operação do equipamento.",
  risco: "A operação da serra fita envolve uma lâmina de corte contínua em movimento, apresentando risco de cortes graves em caso de contato direto. Há também risco de projeção de partículas, aprisionamento de mãos ou roupas e ruído durante a operação, sendo obrigatório o uso de EPIs.",
  nivelRisco: 5,
},

"Serra Fita Horizontal": {
  tags: ["Térreo Maker", "Uso Supervisionado"],
  descricao: "Utilizada para o seccionamento de barras, tubos e perfis metálicos com cortes precisos, por meio de lâmina contínua em operação horizontal.",
  marca: "Clark",
  modelo: "SF 250",
  volume: "N/A",
  softwares: "N/A",
  materiais: ["Aço", "Alumínio", "Latão", "Tubos e perfis metálicos"],
  uso: "O uso deste equipamento requer obrigatoriamente o acompanhamento de um técnico responsável e o uso de EPIs completos.",
  risco: "A lâmina de corte em movimento contínuo representa risco de cortes graves. O contato com a lâmina durante operação ou parada deve ser evitado. Mantenha mãos e roupas afastadas das partes móveis.",
  nivelRisco: 4,
},

"Torno Convencional": {
  tags: ["Térreo Maker", "Uso Supervisionado"],
  descricao: "Utilizado para a fabricação e acabamento de peças cilíndricas por meio da rotação do material e do uso de ferramentas de corte.",
  marca: "Clark",
  modelo: "TL 4210",
  volume: "N/A",
  softwares: "N/A",
  materiais: ["Aço", "Alumínio", "Latão"],
  uso: "O uso do torno requer obrigatoriamente o acompanhamento de um técnico responsável e o uso de EPIs completos.",
  risco: "Risco de estilhaços e contato com partes móveis. Mantenha o cabelo preso e não utilize roupas folgadas, luvas ou acessórios como anéis durante a operação.",
  nivelRisco: 3,
},

"Fresadora Ferramenteira": {
  tags: ["Térreo Maker", "Uso Supervisionado"],
  descricao: "Utilizada para a usinagem de peças complexas por meio de fresas em diferentes eixos, permitindo a confecção de superfícies planas, perfis e cavidades com alta precisão.",
  marca: "Clark",
  modelo: "FFH 4",
  volume: "N/A",
  softwares: "N/A",
  materiais: ["Aço", "Alumínio", "Latão"],
  uso: "O uso da fresadora requer obrigatoriamente o acompanhamento de um técnico responsável e o uso de EPIs completos.",
  risco: "A fresa em alta rotação representa risco de cortes e projeção de cavacos. Nunca opere sem proteção ocular. Mantenha cabelo preso e evite roupas folgadas ou acessórios que possam ser aprisionados pelas partes móveis.",
  nivelRisco: 4,
},

"Furadeira de Bancada": {
  tags: ["Térreo Maker", "Necessário treinamento"],
  descriçao: "Utilizada para a perfuração precisa de materiais em posição vertical, com controle de profundidade e rotação ajustável conforme o material e diâmetro da broca.",
  marca: "A definir",
  modelo: "A definir",
  volume: "N/A",
  softwares: "N/A",
  materiais: ["Aço", "Alumínio", "Madeiras", "Plásticos"],
  uso: "Este dispositivo pode ser utilizado de forma autônoma; para isso, é necessário concluir o treinamento de segurança 'Furadeira de Bancada', com duração de aproximadamente 30 minutos.",
  risco: "Risco de aprisionamento de cabelo, roupas ou luvas na broca em rotação. Nunca utilize luvas durante a operação. Fixe sempre o material com grampo ou morsa antes de perfurar.",
  nivelRisco: 3,
},

"Vacuum Forming": {
  tags: ["Térreo Maker", "Necessário treinamento"],
  descricao: "Utilizado para a conformação de peças termoplásticas por meio de calor e vácuo, permitindo a produção de formas tridimensionais a partir de chapas planas.",
  marca: "A definir",
  modelo: "VFBPD4060",
  volume: "N/A",
  softwares: "N/A",
  materiais: ["ABS", "PETG", "PS", "PVC"],
  uso: "Este dispositivo pode ser utilizado de forma autônoma; para isso, é necessário concluir o treinamento de segurança 'Vacuum Forming', com duração de aproximadamente 30 a 60 minutos.",
  risco: "O material termoplástico aquecido pode atingir temperaturas elevadas e causar queimaduras por contato. Aguarde o resfriamento adequado antes de manusear as peças. Use luvas de proteção térmica ao operar o equipamento.",
  nivelRisco: 2,
},

"Furadeira de Bancada com Rosqueadeira": {
  tags: ["Térreo Maker", "Uso Supervisionado"],
  descricao: "Utilizada para perfuração e rosqueamento de materiais metálicos com controle preciso de profundidade e rotação, com 5 velocidades ajustáveis.",
  marca: "A definir",
  modelo: "CM2 5VEL 750W 380V",
  volume: "N/A",
  softwares: "N/A",
  materiais: ["Aço", "Alumínio", "Latão"],
  uso: "O uso deste equipamento requer obrigatoriamente o acompanhamento de um técnico responsável e o uso de EPIs completos.",
  risco: "Risco de aprisionamento de cabelo, roupas ou luvas na broca em rotação. Nunca utilize luvas durante a operação. Fixe sempre o material com grampo ou morsa antes de perfurar.",
  nivelRisco: 3,
},

"Furadeira de Bancada - Marcenaria": {
  tags: ["Mezanino Maker", "Necessário treinamento"],
  descricao: "Utilizada para a perfuração precisa de materiais como madeira, MDF e plásticos, com controle de profundidade e velocidade ajustável.",
  marca: "Schulz",
  modelo: "FSB16 TORK 370W",
  volume: "N/A",
  softwares: "N/A",
  materiais: ["Madeiras", "MDF", "Compensados", "Plásticos"],
  uso: "Este dispositivo pode ser utilizado de forma autônoma; para isso, é necessário concluir o treinamento de segurança 'Furadeira de Bancada', com duração de aproximadamente 30 minutos.",
  risco: "Risco de aprisionamento de cabelo, roupas ou luvas na broca em rotação. Nunca utilize luvas durante a operação. Fixe sempre o material com grampo ou morsa antes de perfurar.",
  nivelRisco: 2,
},

// --- FERRAMENTAS ELÉTRICAS ---

"Furadeira de Impacto": {
  tags: ["Lab. CAD/CAE/CAM", "Necessário treinamento"],
  descricao: "Utilizada para perfuração e parafusamento em materiais diversos, com função de impacto para superfícies mais resistentes como alvenaria e concreto.",
  marca: "Bosch",
  modelo: "GSB 16 RE",
  volume: "N/A",
  softwares: "N/A",
  materiais: ["Madeiras", "Metais", "Alvenaria", "Plásticos"],
  uso: "Este dispositivo pode ser utilizado de forma autônoma; para isso, é necessário concluir o treinamento de segurança 'Ferramentas Elétricas Portáteis', com duração de aproximadamente 30 minutos.",
  risco: "Risco de contato com a broca em rotação e projeção de partículas. Use óculos de proteção e fixe bem o material antes de operar. Nunca pressione o gatilho sem que a broca esteja posicionada.",
  nivelRisco: 2,
},

"Serra Tico-Tico": {
  tags: ["Lab. CAD/CAE/CAM", "Necessário treinamento"],
  descricao: "Utilizada para cortes curvos ou retos em madeira, plásticos e metais leves, com lâmina de movimento alternado e guia de corte ajustável.",
  marca: "Dewalt",
  modelo: "DWE300B2",
  volume: "N/A",
  softwares: "N/A",
  materiais: ["Madeiras", "MDF", "Plásticos", "Metais leves"],
  uso: "Este dispositivo pode ser utilizado de forma autônoma; para isso, é necessário concluir o treinamento de segurança 'Ferramentas Elétricas Portáteis', com duração de aproximadamente 30 minutos.",
  risco: "Risco de cortes por contato com a lâmina em movimento. Mantenha as mãos afastadas da linha de corte e utilize óculos de proteção. Fixe o material adequadamente antes de iniciar o corte.",
  nivelRisco: 3,
},

"Lixadeira Orbital": {
  tags: ["Lab. CAD/CAE/CAM", "Necessário treinamento"],
  descricao: "Utilizada para lixamento e acabamento de superfícies planas, com movimento orbital que reduz marcas de lixa e proporciona acabamento uniforme.",
  marca: "Bosch",
  modelo: "GSS 140",
  volume: "N/A",
  softwares: "N/A",
  materiais: ["Madeiras", "MDF", "Plásticos", "Metais"],
  uso: "Este dispositivo pode ser utilizado de forma autônoma; para isso, é necessário concluir o treinamento de segurança 'Ferramentas Elétricas Portáteis', com duração de aproximadamente 30 minutos.",
  risco: "Risco de inalação de partículas finas de poeira durante o lixamento. Use máscara de proteção respiratória e óculos. Opere sempre em ambiente ventilado ou com sistema de aspiração acoplado.",
  nivelRisco: 1,
},

"Lixadeira Roto-Orbital": {
  tags: ["Lab. CAD/CAE/CAM", "Necessário treinamento"],
  descricao: "Utilizada para lixamento e acabamento de superfícies com movimento roto-orbital, combinando velocidade de remoção de material e qualidade de acabamento.",
  marca: "Dewalt",
  modelo: "DWE6421-B2",
  volume: "N/A",
  softwares: "N/A",
  materiais: ["Madeiras", "MDF", "Plásticos", "Metais"],
  uso: "Este dispositivo pode ser utilizado de forma autônoma; para isso, é necessário concluir o treinamento de segurança 'Ferramentas Elétricas Portáteis', com duração de aproximadamente 30 minutos.",
  risco: "Risco de inalação de partículas finas de poeira durante o lixamento. Use máscara de proteção respiratória e óculos. Opere sempre em ambiente ventilado ou com sistema de aspiração acoplado.",
  nivelRisco: 1,
},

"Lixadeira Cinta/Disco": {
  tags: ["Lab. CAD/CAE/CAM", "Necessário treinamento"],
  descricao: "Utilizada para lixamento e desbaste de peças por meio de cinta e disco abrasivo, com mesa de apoio ajustável para controle de ângulo e acabamento.",
  marca: "Manrod",
  modelo: "MR-47",
  volume: "N/A",
  softwares: "N/A",
  materiais: ["Madeiras", "MDF", "Plásticos", "Metais leves"],
  uso: "Este dispositivo pode ser utilizado de forma autônoma; para isso, é necessário concluir o treinamento de segurança 'Ferramentas de Bancada', com duração de aproximadamente 30 minutos.",
  risco: "Risco de abrasão por contato com a cinta ou disco em movimento. Mantenha os dedos afastados da superfície abrasiva e utilize óculos de proteção. Nunca lixe peças sem apoiá-las na mesa.",
  nivelRisco: 2,
},

"Esmerilhadeira Angular 4½\"": {
  tags: ["Lab. CAD/CAE/CAM", "Necessário treinamento"],
  descricao: "Utilizada para corte, desbaste e acabamento de metais por meio de discos abrasivos em alta rotação, com versatilidade para diferentes tipos de disco.",
  marca: "Dewalt",
  modelo: "DWE4118-B2",
  volume: "N/A",
  softwares: "N/A",
  materiais: ["Aço", "Alumínio", "Concreto", "Metais em geral"],
  uso: "Este dispositivo pode ser utilizado de forma autônoma; para isso, é necessário concluir o treinamento de segurança 'Ferramentas Elétricas Portáteis', com duração de aproximadamente 30 minutos.",
  risco: "Risco de projeção de faíscas e fragmentos do disco em alta rotação. Use obrigatoriamente óculos de segurança, protetor facial, luvas e protetor auricular. Nunca remova a proteção do disco durante a operação.",
  nivelRisco: 4,
},

"Esmerilhadeira Angular 9\"": {
  tags: ["Lab. CAD/CAE/CAM", "Necessário treinamento"],
  descricao: "Utilizada para corte e desbaste de materiais de maior espessura, com disco de 9 polegadas e alta potência para trabalhos mais exigentes.",
  marca: "Bosch",
  modelo: "GWS 2200-230",
  volume: "N/A",
  softwares: "N/A",
  materiais: ["Aço", "Concreto", "Pedras", "Metais em geral"],
  uso: "Este dispositivo pode ser utilizado de forma autônoma; para isso, é necessário concluir o treinamento de segurança 'Ferramentas Elétricas Portáteis', com duração de aproximadamente 30 minutos.",
  risco: "Risco elevado de projeção de faíscas e fragmentos em alta rotação devido ao tamanho do disco. Use obrigatoriamente óculos de segurança, protetor facial, luvas e protetor auricular. Nunca utilize disco danificado ou inadequado para o equipamento.",
  nivelRisco: 4,
},

"Moto Esmeril de Bancada": {
  tags: ["Lab. CAD/CAE/CAM", "Necessário treinamento"],
  descricao: "Utilizado para afiação de ferramentas de corte e desbaste de peças metálicas por meio de rebolos abrasivos fixos em bancada.",
  marca: "Motomil",
  modelo: "NR12 220V 1CV",
  volume: "N/A",
  softwares: "N/A",
  materiais: ["Aço", "Alumínio", "Ferramentas de corte"],
  uso: "Este dispositivo pode ser utilizado de forma autônoma; para isso, é necessário concluir o treinamento de segurança 'Ferramentas de Bancada', com duração de aproximadamente 30 minutos.",
  risco: "Risco de projeção de fagulhas e partículas abrasivas. Use obrigatoriamente óculos de proteção ou protetor facial. Nunca apoie a peça lateralmente no rebolo e mantenha o descanso de peça sempre ajustado próximo ao rebolo.",
  nivelRisco: 3,
},

"Serra Rápida": {
  tags: ["Lab. CAD/CAE/CAM", "Uso Supervisionado"],
  descricao: "Utilizada para o corte de metais como barras, tubos e perfis, com disco abrasivo de alta rotação para cortes retos com velocidade e precisão.",
  marca: "Bosch",
  modelo: "GCO 14-24",
  volume: "N/A",
  softwares: "N/A",
  materiais: ["Aço", "Alumínio", "Tubos", "Perfis metálicos"],
  uso: "O uso deste equipamento requer obrigatoriamente o acompanhamento de um técnico responsável e o uso de EPIs completos.",
  risco: "Risco de projeção intensa de faíscas e fragmentos do disco abrasivo em alta rotação. Use obrigatoriamente protetor facial, luvas, protetor auricular e avental de raspa. Nunca opere sem que a peça esteja fixada na morsa do equipamento.",
  nivelRisco: 5,
},

"Serra Circular Portátil": {
  tags: ["Lab. CAD/CAE/CAM", "Necessário treinamento"],
  descricao: "Utilizada para cortes retos em madeira, MDF e materiais em chapa, com disco intercambiável e guia de corte ajustável.",
  marca: "Bosch",
  modelo: "GKS 150",
  volume: "N/A",
  softwares: "N/A",
  materiais: ["Madeiras", "MDF", "Compensados"],
  uso: "Este dispositivo pode ser utilizado de forma autônoma; para isso, é necessário concluir o treinamento de segurança 'Ferramentas Elétricas Portáteis', com duração de aproximadamente 30 minutos.",
  risco: "Risco de cortes graves por contato com o disco em alta rotação e projeção de partículas. Use obrigatoriamente óculos de proteção e fixe bem o material antes de cortar. Nunca bloqueie a proteção do disco.",
  nivelRisco: 4,
},

"Serra de Mármore": {
  tags: ["Lab. CAD/CAE/CAM", "Necessário treinamento"],
  descricao: "Utilizada para o corte de materiais pétreos, cerâmicas e materiais compostos, com disco diamantado e profundidade de corte ajustável.",
  marca: "Makita",
  modelo: "4100NH2Z",
  volume: "N/A",
  softwares: "N/A",
  materiais: ["Cerâmica", "Pedras", "Materiais compostos"],
  uso: "Este dispositivo pode ser utilizado de forma autônoma; para isso, é necessário concluir o treinamento de segurança 'Ferramentas Elétricas Portáteis', com duração de aproximadamente 30 minutos.",
  risco: "Risco de cortes graves e projeção de fragmentos em alta velocidade. Use obrigatoriamente óculos de proteção, protetor facial e máscara contra poeira. Opere sempre com a guia de apoio encostada na superfície de corte.",
  nivelRisco: 4,
},

"Micro Retífica": {
  tags: ["Lab. CAD/CAE/CAM", "Necessário treinamento"],
  descricao: "Utilizada para acabamento, gravação, polimento e corte de materiais com alta precisão, por meio de acessórios intercambiáveis em alta rotação.",
  marca: "Dremel",
  modelo: "75W 35000RPM Kit 36 peças",
  volume: "N/A",
  softwares: "N/A",
  materiais: ["Madeiras", "Metais", "Plásticos", "Vidros", "Cerâmica"],
  uso: "Este dispositivo pode ser utilizado de forma autônoma; para isso, é necessário concluir o treinamento de segurança 'Ferramentas Elétricas Portáteis', com duração de aproximadamente 30 minutos.",
  risco: "Risco de projeção de partículas e fragmentos dos acessórios em alta rotação. Use obrigatoriamente óculos de proteção. Verifique sempre o estado e a fixação do acessório antes de ligar o equipamento.",
  nivelRisco: 2,
},

"Lixadeira/Politriz Angular": {
  tags: ["Lab. CAD/CAE/CAM", "Necessário treinamento"],
  descricao: "Utilizada para polimento, lixamento fino e acabamento de superfícies metálicas e pintadas, com velocidade variável e baixa rotação para maior controle.",
  marca: "Dewalt",
  modelo: "DWP849XB2",
  volume: "N/A",
  softwares: "N/A",
  materiais: ["Metais", "Lataria", "Superfícies pintadas"],
  uso: "Este dispositivo pode ser utilizado de forma autônoma; para isso, é necessário concluir o treinamento de segurança 'Ferramentas Elétricas Portáteis', com duração de aproximadamente 30 minutos.",
  risco: "Risco de aprisionamento do disco de polimento em altas rotações. Use óculos de proteção e evite pressão excessiva sobre a superfície. Certifique-se de que o disco esteja corretamente fixado antes de operar.",
  nivelRisco: 2,
},

"Afiadora Universal de Ferramentas": {
  tags: ["Mezanino Maker", "Uso Supervisionado"],
  descricao: "Utilizada para a afiação precisa de ferramentas de corte como brocas, fresas e machos, por meio de rebolos de precisão com ajuste de ângulo.",
  marca: "VB",
  modelo: "U3 380V",
  volume: "N/A",
  softwares: "N/A",
  materiais: ["Aço rápido", "Metal duro", "Ferramentas de corte"],
  uso: "O uso deste equipamento requer obrigatoriamente o acompanhamento de um técnico responsável e o uso de EPIs completos.",
  risco: "Risco de projeção de fagulhas e partículas abrasivas. Use obrigatoriamente óculos de proteção ou protetor facial. A regulagem incorreta dos ângulos de afiação pode danificar a ferramenta e causar acidentes durante o uso posterior.",
  nivelRisco: 3,
}

    
    
};